spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    password: 123456
    username: jdbc_user
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


