spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_telegram_bot
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

